#pragma once
#include <string>

const std::string id_to_name(const int id)
{
  switch(id)
  {
    case 110: return "Esc";
    case 112: return "F1";
    case 113: return "F2";
    case 114: return "F3";
    case 115: return "F4";
    case 116: return "F5";
    case 117: return "F6";
    case 118: return "F7";
    case 119: return "F8";
    case 120: return "F9";
    case 121: return "F10";
    case 122: return "F11";
    case 123: return "F12";
    case 124: return "Print Scr.";
    case 125: return "Scroll Lock";
    case 126: return "Pause";
    case 1: return "Hankaku/Zenkaku";
    case 2: return "1";
    case 3: return "2";
    case 4: return "3";
    case 5: return "4";
    case 6: return "5";
    case 7: return "6";
    case 8: return "7";
    case 9: return "8";
    case 10: return "9";
    case 11: return "0";
    case 12: return "-";
    case 13: return "^";
    case 14: return "\\(yen)";
    case 15: return "Back space";
    case 16: return "Tab";
    case 17: return "Q";
    case 18: return "W";
    case 19: return "E";
    case 20: return "R";
    case 21: return "T";
    case 22: return "Y";
    case 23: return "U";
    case 24: return "I";
    case 25: return "O";
    case 26: return "P";
    case 27: return "@";
    case 28: return "[";
    case 30: return "CapsLk";
    case 31: return "A";
    case 32: return "S";
    case 33: return "D";
    case 34: return "F";
    case 35: return "G";
    case 36: return "H";
    case 37: return "J";
    case 38: return "K";
    case 39: return "L";
    case 40: return ";";
    case 41: return ":";
    case 42: return "]";
    case 43: return "Enter";
    case 44: return "Shift(left)";
    case 46: return "Z";
    case 47: return "X";
    case 48: return "C";
    case 49: return "V";
    case 50: return "B";
    case 51: return "N";
    case 52: return "M";
    case 53: return ",";
    case 54: return ".";
    case 55: return "/";
    case 56: return "\\(back slash)";
    case 57: return "Shift(right)";
    case 58: return "Ctrl(left)";
    case 127: return "Win.(left)";
    case 60: return "Alt(left)";
    case 131: return "Muhenkan";
    case 61: return "Space";
    case 132: return "Henkan";
    case 133: return "Katanaka/Hiragana";
    case 62: return "Alt(right)";
    case 128: return "Win.(right)";
    case 129: return "App.";
    case 64: return "Ctrl(right)";
    case 75: return "Insert";
    case 76: return "Delete";
    case 80: return "Home";
    case 81: return "End";
    case 85: return "Page Up";
    case 86: return "Page Down";
    case 83: return "Up";
    case 79: return "Left";
    case 84: return "Down";
    case 89: return "Right";
    case 90: return "Num Lock";
    case 91: return "Num 7";
    case 92: return "Num 4";
    case 93: return "Num 1";
    case 95: return "Num /";
    case 96: return "Num 8";
    case 97: return "Num 5";
    case 98: return "Num 2";
    case 99: return "Num 0";
    case 100: return "Num *";
    case 101: return "Num 9";
    case 102: return "Num 6";
    case 103: return "Num 3";
    case 104: return "Num .";
    case 105: return "Num -";
    case 106: return "Num +";
    case 108: return "Num Enter";
  };
  
  return "????";
}
